### ISSUE TITLE
android 点击通知栏消息无法启动应用

### ISSUE THREAD

**Issue by gxly007** [jpush/jpush-hbuilder-demo#7]
您好，我现在遇到这个情况，Android应用被杀死了，但是推送服务被其它应用拉起了，加入了这一段
`        
        
        <service
            android:name="cn.jpush.android.service.DaemonService"
            android:enabled="true"
            android:exported="true">
            <intent-filter >
                <action android:name="cn.jpush.android.intent.DaemonService" />
                <category android:name="com.XXX.XXX"/>
            </intent-filter>
        </service>`

我现在是可以收到消息，但是点击消息的时候无法启动应用，点击通知栏消息没有反应。能否帮看看怎么解决？

**Comment by gxly007** [comment]
在上面描述的情况下，后台抛出异常信息如下：
java.lang.RuntimeException: Unable to start receiver io.dcloud.feature.jpush.JPushReceiver: java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Activity io.dcloud.common.DHInterface.IWebview.getActivity()' on a null object reference
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2760)
	at android.app.ActivityThread.access$1800(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5546)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Activity io.dcloud.common.DHInterface.IWebview.getActivity()' on a null object reference
	at io.dcloud.feature.jpush.JPushService.transmitNotificationOpen(JPushService.java:146)
	at io.dcloud.feature.jpush.JPushReceiver.handlingNotificationOpen(JPushReceiver.java:60)
	at io.dcloud.feature.jpush.JPushReceiver.onReceive(JPushReceiver.java:38)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2753)
	... 8 more

**Comment by lhw5123** [comment]
在你 Android 项目的 manifest.json 里有没有如下的配置项：
![10](https://user-images.githubusercontent.com/6531354/31763888-39c0eba2-b4f2-11e7-955b-11bade5bcbc2.png)

**Comment by gxly007** [comment]
这个配置都有，现在的问题聚焦在，如果应用没有被杀死的情况下，是可以正常跳转并打开的。
如果应用被杀死了，再点击通知消息就没反应了，后台报这个错误：
java.lang.RuntimeException: Unable to start receiver io.dcloud.feature.jpush.JPushReceiver: java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Activity io.dcloud.common.DHInterface.IWebview.getActivity()' on a null object reference
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2760)
at android.app.ActivityThread.access$1800(ActivityThread.java:165)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5546)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.app.Activity io.dcloud.common.DHInterface.IWebview.getActivity()' on a null object reference
at io.dcloud.feature.jpush.JPushService.transmitNotificationOpen(JPushService.java:146)
at io.dcloud.feature.jpush.JPushReceiver.handlingNotificationOpen(JPushReceiver.java:60)
at io.dcloud.feature.jpush.JPushReceiver.onReceive(JPushReceiver.java:38)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2753)
... 8 more

我在想是不是在我们的 onReceive 需要判断应用的状态，如果关掉了，需要启动起来，烦请帮分析看看。

**Comment by lhw5123** [comment]
能说一下具体的应用操作流程吗？我这边好测试一下。
